### PR TITLE
Add config and tests for Lithuanian.

### PR DESCRIPTION
**Pull request by karls**
Hi @rluiten! 👋 

I've added another config, this time for Lithuanian. I don't speak any Lithuanian myself, but we need it for a project, so I've taken the format from here http://www.localeplanet.com/java/lt-LT/index.html.

### CODE REVIEW

**Comment by rluiten** [comment]
This is published in 8.6.1

**Comment by karls** [comment]
Thank you!

**Comment by karls** [comment]
Hmm, for some reason, the new code has not propagated to package.elm-lang.org. 🤔 

http://package.elm-lang.org/packages/rluiten/elm-date-extra/latest

**Comment by rluiten** [comment]
Wow first for me, wonder what I did wrong.
Ill bump version and publish again

**Comment by rluiten** [comment]
Lol i think i know what i forgot publishing again. 8.6.3 should be out shortly

**Comment by karls** [comment]
😄

**Comment by rluiten** [comment]
Ok 8.7.0 is published thanks for catching it.
It did have the config and i18n in it but it was not exposed so the documentation didn't come out.

**Comment by karls** [comment]
Ah, got it! I should've probably done that myself in the pull request. My bad!

Thanks for the release and swift responses!

**Comment by rluiten** [comment]
I've forgotten myself in past to expose modules.
You are lucky I just got home so checked email.

**Pull request merged**
