### PR TITLE
Upgrade to Elm 0.18

### PR DESCRIPTION
**Pull request by joeandaverde**
Still working on verifying I've got all changes. I didn't use elm-format/elm-ugprade because it would change indentation on all files.

### CODE REVIEW

**Comment by joeandaverde** [comment]
I leave the versioning up to you.

**Comment by joeandaverde** [comment]
I also had to upgrade to the latest version of elm-test. I took the test runner code directly from elm-test.  Here's the output.

```Success! Compiled 0 modules.
Successfully generated program.js
CreateTests currentOffsets: (300,360)
DurationTests currentOffsets: (300,360)

TEST RUN PASSED

Passed: 236
Failed: 0

Exit code: 0```

**Comment by rluiten** [comment]
This has been published.
@joeandaverde did you write the Runner.Log and Runner.String classes  your self ?
Seems to be they make life simpler ;), shame they arn't built in.

**Comment by joeandaverde** [comment]
No, I borrowed them from elm test examples.

**Pull request merged**
