### PR TITLE
Add localisation for Estonian.

### PR DESCRIPTION
**Pull request by karls**
Hi @rluiten,

Thanks for this library!

I have added localisation for Estonian, which, admittedly, is a very niche target market, but I needed it and figured I'd contribute it back. 

The date/time formats are taken from http://www.eki.ee/itstandard/2000/FDCC.shtml.en.

Let me know if this needs more work or any other input.

Cheers!

### CODE REVIEW

**Comment by karls** [comment]
Thanks! :tada:

**Comment by rluiten** [comment]
Your quick, I'm just fixing up so all languages and locale date formats are exported properly.
Improving test cases for getConfig to cover them all.
Plan to add at least one format test case for each language as well I think, considering this.

**Comment by karls** [comment]
Cool. I have vendored this library into my project for now. But I'm eager to stop using the vendored version and depend on this properly.

Let me know if you need help with anything and/or clarification.

**Comment by rluiten** [comment]
I have some day light saving issues to track down, but I am pretty sure that will take time so am unwilling to start unless I have allocated a good block of time. So will tidy up an release this with 2 other languages in next few hours I expect.

**Comment by karls** [comment]
Super! Thanks!

**Comment by rluiten** [comment]
Published 8.2.0

**Pull request merged**
