### PR TITLE
updating to 0.17

### PR DESCRIPTION
**Pull request by athanclark**
It's essentially the exact same code, just with `exposing (..)` instead of `where` for the module declarations :)

### CODE REVIEW

**Comment by rluiten** [comment]
Thanks for this.
Still need to update the TestRunner as elementRunner does not exist in elm-community/elm-test it has changed. 
I'll look into this further in next few days.

I have started updating some of my packages, I've already updated stringdistance and mailcheck packages just not date extra yet.

**Comment by athanclark** [comment]
Would you want to keep all of your unit test data with millisecond data? It seems like firefox can't parse date strings like `2015/06/15 10:00:00.123` - those last few digits cause an invalid date error for me.

**Comment by rluiten** [comment]
I knew there were differences but I had not run across that one.
I know how to make milliseconds work in Firefox I may just change the test input to suite I think.

**Comment by rluiten** [comment]
Thanks for your work on the update.
I have modified tests to run on Firefox and Chrome now, keeping the millisecond testing.
I have updated the examples to new Http application format.
Using Elm version standard the next version is 5.0.1 and it is published now.

**Pull request merged**
