### PR TITLE
Names and formats for Polish culture

### PR DESCRIPTION
**Pull request by bartsokol**
Added day/month names and date/time formats for Polish culture (pl-pl)

### CODE REVIEW

**Comment by rluiten** [comment]
I know nothing about polish, so just want to check somethign with you.
Most other languages have upper Case first letter for Day and Month names, is this something that is not the case in Polish as it appears to me at least they are all lower case ?

**Comment by bartsokol** [comment]
Yes, in Poland we don't capitalize names of days of week and months, that's why it's all lowercase. I compared it with some other projects and it looks the same everywhere.

**Comment by rluiten** [comment]
Excellent, I just wanted to double check..
Ill do a release now.

**Comment by rluiten** [comment]
Done :)

**Comment by bartsokol** [comment]
Cool, thanks! :)

**Pull request merged**
