### PR TITLE
Add Russian locale

### PR DESCRIPTION
**Pull request by tvv**

### CODE REVIEW

**Comment by tvv** [comment]
Sorry for previous pull request, i was on hurry.

**Comment by rluiten** [comment]
Hi, sorry I havnt had time to get to Elm just enough time to keep an eye on Pull Requests.
Was planning to merge this weekend. @tvv

**Comment by tvv** [comment]
I just merged german locale and made some changes for local usage. 

You should revert package info. Or wait for i'll do.

**Comment by tvv** [comment]
Correct candidate - https://github.com/relabsoss/elm-date-extra/tree/ru_de_locale

**Comment by rluiten** [comment]
I am really not sure how to create a pull request from your branch to mine, I tried but it has conflicts and I believe that makes merges on github possible. I can drive github but I am no expert.

**Comment by tvv** [comment]
It should be done over console, but its not trivial)

**Comment by rluiten** [comment]
I understand the local process, and believe i did it right fixed the few merge conflicst., but now I don't have the ru_ru configs in branch.
I am going to reset master back to when i merged the german translation and try again

**Comment by tvv** [comment]
Just merge  https://github.com/relabsoss/elm-date-extra/tree/ru_de_locale branch which already has DE locale modules.

**Comment by rluiten** [comment]
Ok the reset made it simple, published 8.4.0.
Cheers!

**Comment by tvv** [comment]
Nice)

**Pull request merged**
